// ... existing code ...
import StudentUpload from './components/StudentUpload';
// ... existing code ...

// Inside your router configuration
<Routes>
  // ... existing routes ...
  <Route path="/student-upload" element={<StudentUpload />} />
  // ... existing routes ...
</Routes>
// ... existing code ...